tasks:

  slay:
    weight: 1

    zombie:
      weight: 1
      min: 16
      max: 64

    skeleton:
      weight: 1
      min: 20
      max: 48

  acquire:
    weight: 1

    #enchanted_book_1:
      #weight: 1
      #enchantments:
        #power: 3
        #infinity: 1
      #min: 1
      #max: 1

    sand:
      weight: 1
      min: 64
      max: 128

    sugar_cane:
      weight: 1
      min: 64
      max: 128

rewards:

  enchanted_book_1:
    weight: 1
    enchantments:
      power: 6