main: ee.kmtster.xmastasks.XmasTasksPlugin
name: ChristmasTasks
version: 1.0
api-version: 1.16
description: Christmas Tasks
author: kmtster

commands:
  xmastasks:
    usage: /<command>
    description: Open the Christmas Tasks UI