main: ee.kmtster.missions.MissionsPlugin
name: Missions
version: 1.0
api-version: 1.16
description: Missions
author: kmtster

commands:
  missions:
    usage: /<command>
    description: Open the Missions UI
    aliases: [xmastasks, xt]